### ISSUE TITLE
Raspberrypi上でのble Discoverableをonにするプログラムの作成

### ISSUE THREAD

**Issue by T3pp31** [T3pp31/BLE_Blockchain#21]
raspberrypiのbleではセキュリティの観点からか，ble検索にかからないようになっているので，定期的に以下のコマンドを実行する必要がある. つまりサーバーとして情報を受け取るためには以下のコマンドを毎回行う必要があるので，サーバを起動するときに以下のコマンドを自動的に実行するように変更する必要がある．

$ bluetoothctl
$ discoverable on

以上のことをPythonのライブラリであるsubprocess等を用いて実装する必要がある

**Comment by KeiGoMiyamaE** [comment]
subprocessを用いて、pythonを実行することでbluetoothctl、discoverable onにできた。ただし、起動時に自動実行される点については、Linuxの起動処理を管理する機能であるsystemdで実現できると考えたが、未だできていない。

**Comment by T3pp31** [comment]
上記コードをブランチ，プルリクエストを作成して出してください．
起動時に自動実行する必要はなく，BLEで通信する時だけオンにしたいので，問題ないです
