### ISSUE TITLE
Scanをした際(discover.pyの）の出力データがDataFrame形式になっていない？

### ISSUE THREAD

**Issue by T3pp31** [T3pp31/BLE_Blockchain#32]
タイトルの通りである．
調査が必要なので，取り組める人がいたらお願いしたいです

**Comment by T3pp31** [comment]
調査方法としては，
scan関数を実行後,
df.to_csv('ファイル名.csv')
を実行し，csvファイルが生成されるかを確認して欲しい．

**Comment by Kazhirotsuka** [comment]
scan関数実行後df.to_csv('ファイル名.csv')してみたんですがdfが定義されてないよと言われました。(実行は出来ました)
関数の中にぶち込んでみたら一応csvファイル生成は出来たっぽいです。
![2022-10-29-012139_1920x1080_scrot](https://user-images.githubusercontent.com/67130583/198687134-3e3834fb-8178-4925-94a7-22ecd6ffcb49.png)

**Comment by T3pp31** [comment]
scan関数実行後df.to_csv('ファイル名.csv')してみたんですがdfが定義されてないよと言われました。(実行は出来ました)
ここがなんでなるのかなーと思ってます．
df = scan()で，dfを作るので，データフレームが帰ってきていないと．必要なもののみの抽出が難しいので．．．

**Comment by T3pp31** [comment]
https://aish.dev/python/20200711_asyncio_task.html
この問題かもしれません．．．

**Comment by T3pp31** [comment]
Returnでデータフレームが返せていない可能性があるので，Returnでリストを返して，関数外でDataFrame形式へ変換する．
